### ISSUE TITLE
isNetworkSaved(String ssid) - Not good enough. We need comparision based on BSSID. 

### ISSUE THREAD

**Issue by SamarthaKV29** [isuPatches/android-wisefy#149]
Most of the times SSID is not good enough. There might be multiple networks with same SSID, different BSSID. If you know any workaround for this, please suggest.

**Comment by isuPatches** [comment]
@SamarthaKV29 Apologies for the delay.  Just wanted to acknowledge that I have reviewed this ticket and will be working through some options and ideas to help you with this problem.  I don't have an answer just yet.

**Comment by isuPatches** [comment]
A new API will need to be added for this.  This can be added into an early release candidate of 5.x

**Comment by isuPatches** [comment]
I have not forgotten about this, it will be slated for 5.0.0...first I would like to refocus on CI and documentation so that a true 5.0.0 can be released.  Thank you for your patience.
